type ProcessPhase = 'A' | 'B' | 'C' | 'coolDown' | 'general';

interface ProcessStep {
  id: string;
  order: number;
  title: string;
  description?: string;
  phase?: ProcessPhase;
  tempC?: number | null;
  timeMin?: number | null;
  notes?: string;
}

export interface ProcessTemplate {
  id: string;
  name: string;
  tags: string[];
  steps: ProcessStep[];
}

export const processTemplates: ProcessTemplate[] = [
  {
    id: 'ow-emulsion-hot-hot',
    name: 'O/W Emulsion (Hot/Hot)',
    tags: ['emulsion', 'oil-water', 'hot', 'creams', 'moisturizer'],
    steps: [
      {
        id: 'step-1',
        order: 1,
        title: 'Heat Phase A (Oil Phase)',
        phase: 'A',
        tempC: 75,
        timeMin: 15,
        description: 'Combine all oil-soluble ingredients (emulsifiers, oils, butters, waxes) in a heat-resistant container.',
        notes: 'Maintain temperature until Phase B is ready.',
      },
      {
        id: 'step-2',
        order: 2,
        title: 'Heat Phase B (Water Phase)',
        phase: 'B',
        tempC: 75,
        timeMin: 15,
        description: 'Combine water-soluble ingredients (water, humectants, water-soluble actives) in a separate container.',
        notes: 'Heat to same temperature as Phase A.',
      },
      {
        id: 'step-3',
        order: 3,
        title: 'Combine Phases',
        phase: 'general',
        tempC: 75,
        timeMin: 5,
        description: 'Slowly add Phase B to Phase A while stirring continuously. Use a whisk or mechanical stirrer.',
        notes: 'Maintain temperature during combination.',
      },
      {
        id: 'step-4',
        order: 4,
        title: 'Emulsification',
        phase: 'general',
        tempC: 70,
        timeMin: 10,
        description: 'Continue stirring vigorously until emulsion forms. Use stick blender if needed.',
        notes: 'Watch for phase separation. If it occurs, increase stirring speed.',
      },
      {
        id: 'step-5',
        order: 5,
        title: 'Cool Down',
        phase: 'coolDown',
        tempC: 40,
        timeMin: null,
        description: 'Allow mixture to cool while stirring occasionally. Monitor temperature.',
        notes: 'Cool to below 40°C before adding heat-sensitive ingredients.',
      },
      {
        id: 'step-6',
        order: 6,
        title: 'Add Phase C (Heat-Sensitive)',
        phase: 'C',
        tempC: 35,
        timeMin: 5,
        description: 'Add preservatives, fragrances, and other heat-sensitive ingredients.',
        notes: 'Ensure temperature is below 40°C.',
      },
      {
        id: 'step-7',
        order: 7,
        title: 'Final Mixing',
        phase: 'general',
        tempC: null,
        timeMin: 5,
        description: 'Stir gently until all ingredients are well incorporated.',
        notes: 'Avoid introducing air bubbles.',
      },
      {
        id: 'step-8',
        order: 8,
        title: 'Packaging',
        phase: 'general',
        tempC: null,
        timeMin: null,
        description: 'Fill into clean, sanitized containers while still warm.',
        notes: 'Label with batch number and date.',
      },
    ],
  },
  {
    id: 'anhydrous-balm',
    name: 'Anhydrous Balm',
    tags: ['anhydrous', 'balm', 'oil-based', 'butter', 'wax'],
    steps: [
      {
        id: 'step-1',
        order: 1,
        title: 'Melt Hard Butters/Waxes',
        phase: 'A',
        tempC: 65,
        timeMin: 10,
        description: 'Combine hard butters (shea, cocoa) and waxes in a heat-resistant container. Heat until fully melted.',
        notes: 'Do not overheat. Maintain gentle heat.',
      },
      {
        id: 'step-2',
        order: 2,
        title: 'Add Liquid Oils',
        phase: 'A',
        tempC: 60,
        timeMin: 5,
        description: 'Add liquid carrier oils and stir until homogeneous.',
        notes: 'Temperature should be consistent throughout.',
      },
      {
        id: 'step-3',
        order: 3,
        title: 'Add Active Ingredients',
        phase: 'A',
        tempC: 50,
        timeMin: 5,
        description: 'Add oil-soluble actives, vitamins, and other active ingredients.',
        notes: 'Stir gently to avoid oxidation.',
      },
      {
        id: 'step-4',
        order: 4,
        title: 'Cool Down',
        phase: 'coolDown',
        tempC: 35,
        timeMin: null,
        description: 'Allow mixture to cool while stirring occasionally.',
        notes: 'Cool to below 40°C before adding heat-sensitive ingredients.',
      },
      {
        id: 'step-5',
        order: 5,
        title: 'Add Fragrance/Preservatives',
        phase: 'C',
        tempC: 35,
        timeMin: 3,
        description: 'Add essential oils, fragrances, and preservatives if needed.',
        notes: 'Ensure temperature is appropriate for heat-sensitive ingredients.',
      },
      {
        id: 'step-6',
        order: 6,
        title: 'Final Mixing',
        phase: 'general',
        tempC: null,
        timeMin: 5,
        description: 'Stir until completely homogeneous and smooth.',
        notes: 'Check for any unmelted particles.',
      },
      {
        id: 'step-7',
        order: 7,
        title: 'Packaging',
        phase: 'general',
        tempC: null,
        timeMin: null,
        description: 'Fill into containers while still slightly warm for easier pouring.',
        notes: 'Label with batch number and date.',
      },
    ],
  },
  {
    id: 'water-based-serum',
    name: 'Water-Based Serum/Toner',
    tags: ['water-based', 'serum', 'toner', 'liquid', 'actives'],
    steps: [
      {
        id: 'step-1',
        order: 1,
        title: 'Prepare Base Water',
        phase: 'B',
        tempC: null,
        timeMin: null,
        description: 'Measure and prepare purified water or hydrosol base.',
        notes: 'Use distilled or deionized water for best results.',
      },
      {
        id: 'step-2',
        order: 2,
        title: 'Dissolve Water-Soluble Ingredients',
        phase: 'B',
        tempC: null,
        timeMin: 5,
        description: 'Add humectants (glycerin, hyaluronic acid) and water-soluble actives. Stir until fully dissolved.',
        notes: 'Some ingredients may require gentle heating to dissolve.',
      },
      {
        id: 'step-3',
        order: 3,
        title: 'Add pH Adjusters',
        phase: 'B',
        tempC: null,
        timeMin: 2,
        description: 'Adjust pH to target range (typically 5.0-6.5) using citric acid or sodium hydroxide solution.',
        notes: 'Test pH with pH strips or meter.',
      },
      {
        id: 'step-4',
        order: 4,
        title: 'Add Preservatives',
        phase: 'B',
        tempC: null,
        timeMin: 3,
        description: 'Add preservative system and stir until fully incorporated.',
        notes: 'Follow preservative manufacturer guidelines for temperature and pH.',
      },
      {
        id: 'step-5',
        order: 5,
        title: 'Add Fragrance (Optional)',
        phase: 'C',
        tempC: null,
        timeMin: 2,
        description: 'Add essential oils or fragrance if desired.',
        notes: 'Use water-soluble or solubilized fragrances.',
      },
      {
        id: 'step-6',
        order: 6,
        title: 'Final Mixing',
        phase: 'general',
        tempC: null,
        timeMin: 5,
        description: 'Stir gently until all ingredients are well mixed.',
        notes: 'Avoid excessive agitation to prevent foaming.',
      },
      {
        id: 'step-7',
        order: 7,
        title: 'Filtration (Optional)',
        phase: 'general',
        tempC: null,
        timeMin: null,
        description: 'Filter through fine mesh or filter paper if clarity is required.',
        notes: 'Skip if not needed for product type.',
      },
      {
        id: 'step-8',
        order: 8,
        title: 'Packaging',
        phase: 'general',
        tempC: null,
        timeMin: null,
        description: 'Fill into clean, sanitized containers.',
        notes: 'Label with batch number and date.',
      },
    ],
  },
  {
    id: 'ow-emulsion-hot-cold',
    name: 'O/W Emulsion (Hot/Cold)',
    tags: ['emulsion', 'oil-water', 'hot', 'cold', 'creams'],
    steps: [
      {
        id: 'step-1',
        order: 1,
        title: 'Heat Phase A (Oil Phase)',
        phase: 'A',
        tempC: 75,
        timeMin: 15,
        description: 'Combine all oil-soluble ingredients (emulsifiers, oils, butters, waxes) in a heat-resistant container.',
        notes: 'Heat until all solid ingredients are melted and mixture is homogeneous.',
      },
      {
        id: 'step-2',
        order: 2,
        title: 'Prepare Phase B (Water Phase)',
        phase: 'B',
        tempC: null,
        timeMin: null,
        description: 'Combine water-soluble ingredients (water, humectants, water-soluble actives) at room temperature.',
        notes: 'Keep water phase at room temperature. Do not heat.',
      },
      {
        id: 'step-3',
        order: 3,
        title: 'Combine Phases',
        phase: 'general',
        tempC: 70,
        timeMin: 5,
        description: 'Slowly add Phase B (cold) to Phase A (hot) while stirring continuously.',
        notes: 'Temperature gradient helps with emulsion formation.',
      },
      {
        id: 'step-4',
        order: 4,
        title: 'Emulsification',
        phase: 'general',
        tempC: 65,
        timeMin: 10,
        description: 'Continue stirring vigorously until emulsion forms. Use stick blender if needed.',
        notes: 'Watch for phase separation. Increase stirring speed if needed.',
      },
      {
        id: 'step-5',
        order: 5,
        title: 'Cool Down',
        phase: 'coolDown',
        tempC: 40,
        timeMin: null,
        description: 'Allow mixture to cool while stirring occasionally. Monitor temperature.',
        notes: 'Cool to below 40°C before adding heat-sensitive ingredients.',
      },
      {
        id: 'step-6',
        order: 6,
        title: 'Add Phase C (Heat-Sensitive)',
        phase: 'C',
        tempC: 35,
        timeMin: 5,
        description: 'Add preservatives, fragrances, and other heat-sensitive ingredients.',
        notes: 'Ensure temperature is below 40°C.',
      },
      {
        id: 'step-7',
        order: 7,
        title: 'Final Mixing',
        phase: 'general',
        tempC: null,
        timeMin: 5,
        description: 'Stir gently until all ingredients are well incorporated.',
        notes: 'Avoid introducing air bubbles.',
      },
      {
        id: 'step-8',
        order: 8,
        title: 'Packaging',
        phase: 'general',
        tempC: null,
        timeMin: null,
        description: 'Fill into clean, sanitized containers while still warm.',
        notes: 'Label with batch number and date.',
      },
    ],
  },
  {
    id: 'surfactant-cleanser-cold-blend',
    name: 'Surfactant Cleanser/Shampoo (Cold Blend)',
    tags: ['surfactant', 'cleanser', 'shampoo', 'cold', 'foaming'],
    steps: [
      {
        id: 'step-1',
        order: 1,
        title: 'Prepare Base Water',
        phase: 'B',
        tempC: null,
        timeMin: null,
        description: 'Measure and prepare purified water or hydrosol base at room temperature.',
        notes: 'Use distilled or deionized water for best results.',
      },
      {
        id: 'step-2',
        order: 2,
        title: 'Add Primary Surfactants',
        phase: 'B',
        tempC: null,
        timeMin: 5,
        description: 'Slowly add primary surfactants (SLES, SLS, cocamidopropyl betaine) to water while stirring.',
        notes: 'Add slowly to prevent foaming. Stir gently.',
      },
      {
        id: 'step-3',
        order: 3,
        title: 'Add Secondary Surfactants',
        phase: 'B',
        tempC: null,
        timeMin: 5,
        description: 'Add secondary surfactants and amphoterics. Continue stirring until clear and homogeneous.',
        notes: 'Allow foam to settle if excessive.',
      },
      {
        id: 'step-4',
        order: 4,
        title: 'Add Thickeners',
        phase: 'B',
        tempC: null,
        timeMin: 10,
        description: 'Add thickeners (salt, PEG-150, xanthan gum) if needed. Stir until fully dissolved.',
        notes: 'Some thickeners may require time to fully hydrate.',
      },
      {
        id: 'step-5',
        order: 5,
        title: 'Add Conditioning Agents',
        phase: 'B',
        tempC: null,
        timeMin: 5,
        description: 'Add conditioning agents (silicones, fatty alcohols, panthenol) if included.',
        notes: 'Ensure proper dispersion.',
      },
      {
        id: 'step-6',
        order: 6,
        title: 'Add pH Adjusters',
        phase: 'B',
        tempC: null,
        timeMin: 3,
        description: 'Adjust pH to target range (typically 5.0-6.5) using citric acid or sodium hydroxide solution.',
        notes: 'Test pH with pH strips or meter. Critical for product stability.',
      },
      {
        id: 'step-7',
        order: 7,
        title: 'Add Preservatives and Fragrance',
        phase: 'C',
        tempC: null,
        timeMin: 3,
        description: 'Add preservative system and fragrance. Stir until fully incorporated.',
        notes: 'Follow preservative manufacturer guidelines for pH compatibility.',
      },
      {
        id: 'step-8',
        order: 8,
        title: 'Final Mixing and Testing',
        phase: 'general',
        tempC: null,
        timeMin: 5,
        description: 'Stir gently until all ingredients are well mixed. Test viscosity and clarity.',
        notes: 'Avoid excessive agitation to prevent foaming.',
      },
      {
        id: 'step-9',
        order: 9,
        title: 'Packaging',
        phase: 'general',
        tempC: null,
        timeMin: null,
        description: 'Fill into clean, sanitized containers.',
        notes: 'Label with batch number and date.',
      },
    ],
  },
  {
    id: 'carbomer-gel-neutralization',
    name: 'Carbomer Gel (Neutralization)',
    tags: ['gel', 'carbomer', 'neutralization', 'thickening', 'water-based'],
    steps: [
      {
        id: 'step-1',
        order: 1,
        title: 'Prepare Base Water',
        phase: 'B',
        tempC: null,
        timeMin: null,
        description: 'Measure and prepare purified water at room temperature.',
        notes: 'Use distilled or deionized water. Room temperature is critical.',
      },
      {
        id: 'step-2',
        order: 2,
        title: 'Disperse Carbomer',
        phase: 'B',
        tempC: null,
        timeMin: 15,
        description: 'Slowly sprinkle carbomer powder onto water surface while stirring. Avoid clumping.',
        notes: 'Critical: Add powder slowly to prevent clumping. Stir gently but continuously.',
      },
      {
        id: 'step-3',
        order: 3,
        title: 'Hydrate Carbomer',
        phase: 'B',
        tempC: null,
        timeMin: 30,
        description: 'Allow carbomer to fully hydrate. Mixture will appear cloudy initially.',
        notes: 'Hydration time may vary. Wait until fully dispersed before proceeding.',
      },
      {
        id: 'step-4',
        order: 4,
        title: 'Add Water-Soluble Actives',
        phase: 'B',
        tempC: null,
        timeMin: 10,
        description: 'Add water-soluble ingredients (humectants, actives) and stir until dissolved.',
        notes: 'Ensure all ingredients are fully dissolved before neutralization.',
      },
      {
        id: 'step-5',
        order: 5,
        title: 'Prepare Neutralizer',
        phase: 'general',
        tempC: null,
        timeMin: 5,
        description: 'Prepare neutralizing agent (TEA, sodium hydroxide, or other base) as a dilute solution.',
        notes: 'Use 10-20% solution for better control during neutralization.',
      },
      {
        id: 'step-6',
        order: 6,
        title: 'Neutralization (Critical)',
        phase: 'general',
        tempC: null,
        timeMin: 15,
        description: 'Slowly add neutralizer while stirring continuously. Gel will form as pH approaches 6-7.',
        notes: 'Critical step: Add neutralizer very slowly. Monitor pH continuously. Target pH 6.0-7.0.',
      },
      {
        id: 'step-7',
        order: 7,
        title: 'Check pH and Viscosity',
        phase: 'general',
        tempC: null,
        timeMin: 5,
        description: 'Test pH and adjust if needed. Check gel consistency and clarity.',
        notes: 'pH is critical for gel stability. Adjust carefully if outside target range.',
      },
      {
        id: 'step-8',
        order: 8,
        title: 'Add Preservatives',
        phase: 'C',
        tempC: null,
        timeMin: 3,
        description: 'Add preservative system and stir gently until incorporated.',
        notes: 'Stir gently to avoid breaking gel structure.',
      },
      {
        id: 'step-9',
        order: 9,
        title: 'Add Fragrance (Optional)',
        phase: 'C',
        tempC: null,
        timeMin: 2,
        description: 'Add fragrance if desired. Stir gently.',
        notes: 'Use water-soluble or solubilized fragrances.',
      },
      {
        id: 'step-10',
        order: 10,
        title: 'Final Mixing and Packaging',
        phase: 'general',
        tempC: null,
        timeMin: 5,
        description: 'Stir gently to ensure homogeneity. Fill into clean, sanitized containers.',
        notes: 'Avoid excessive stirring to maintain gel structure. Label with batch number and date.',
      },
    ],
  },
];

